databases:
  - name: django_render_sedori_lab
    region: singapore
    plan: starter
    databaseName: django_render_sedori_lab
    user: django_user

services:
  - type: web
    name: django_render_sedori_lab
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn sedorilab_django.wsgi:application'
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_render_sedori_lab
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true