# Generated by Django 2.2.24 on 2021-08-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cource',
            field=models.CharField(max_length=30, verbose_name='コース'),
        ),
    ]
